# RStudio Connect Deployment Pipeline:
#   1. Create, Upload, & Deploy Content
#   2. Set the Vanity URL
#   3. Update the Access Control List

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: 'RStudio Connect Vars'
- name: CONTENT_DIRECTORY
  value: app-dir
- name: VANITY_NAME
  value: azure-app-NHS

steps:
- task: Bash@3
  displayName: 'Create Upload Deploy'
  inputs:
    filePath: 'create-upload-deploy.sh'
    arguments: 'NHS - R CONTENT'
  env:
    CONNECT_API_KEY: $(CONNECT_API_KEY)
- task: Bash@3
  displayName: 'Set Vanity URL'
  inputs:
    filePath: 'set-vanity-url.sh'
  env:
    CONNECT_API_KEY: $(CONNECT_API_KEY)
- task: Bash@3
  displayName: 'Update Access Control List'
  inputs:
    filePath: 'update-acl.sh'
  env:
    CONNECT_API_KEY: $(CONNECT_API_KEY)