# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: 'RStudio Connect Vars'
- name: CONTENT_DIRECTORY
  value: app-dir
- name: VANITY_NAME
  value: azure-app-NHS

steps:
- task: Bash@3
  displayName: 'Create Upload Deploy'
  inputs:
    filePath: 'create-upload-deploy.sh'
    arguments: 'NHS - R CONTENT'
  env:
    CONNECT_API_KEY: $(CONNECT_API_KEY)
- task: Bash@3
  displayName: 'Set Vanity URL'
  inputs:
    filePath: 'set-vanity-url.sh'
  env:
    CONNECT_API_KEY: $(CONNECT_API_KEY)
- task: Bash@3
  displayName: 'Update Access Control List'
  inputs:
    filePath: 'update-acl.sh'
  env:
    CONNECT_API_KEY: $(CONNECT_API_KEY)